[build]
  base = "src/"
  command = "npm install && npm run build"
  publish = "public"

[build.environment]
  GO_VERSION = "1.12"

[[redirects]]
  from = "/"
  to = "/main/"
  status = 302
  force = true

[[redirects]]
  from = "/index.html"
  to = "/main/"
  status = 302
  force = true
