baseURL = 'https://startpage.mdekort.nl/'
languageCode = 'en-us'
title = 'Startpage'
enableRobotsTXT = true
relativeURLS = true

[params]
  author = 'Melvyn de Kort'
  description = 'A custom startpage with all my important links'
  year = 2022
  sourceCode = 'https://github.com/melvyndekort/startpage'
  custom_css = ["css/custom.css"]
  custom_js = []

[module]
  [[module.imports]]
    path = "github.com/melvyndekort/dracula-hugo-theme"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
